### ISSUE TITLE
Filter FDA-approved, antineoplastic and immunotherapies

### ISSUE THREAD

**Issue by clanna** [cbg-ethz/rDGIdb#1]
Hi,
I currently use DGIdb's web interface to query drug-gene interactions. I was looking to implement it in my R workflow and have recently stumbled across this package. I usually use the FDA-approved and antineoplastic filters when querying (it seems to be a DGIdb 3.0 feature), but looking at rDGIdb's documentation, I haven't found this option. So I have this feature request (or question, if it's currently possible to apply these filters). Thanks!

**Comment by thurnherr** [comment]
Hi there,
Thank you for getting in touch. This filter is not currently available and it is unlikely I will find the time to update the package in the next couple of weeks. Feel free to implement it and send a pull request. And I will be happy to update the package.
Best, Thomas
