### ISSUE TITLE
Error on specific gene sets

### ISSUE THREAD

**Issue by jkanche** [cbg-ethz/rDGIdb#4]
Hello,

 I tried the newest devel version from bioconductor (1.15.1) 

As pointed out in this example - https://github.com/cbg-ethz/rDGIdb/issues/3#issuecomment-700791762

This snippet still fails on the newer version. I am not sure what the actual issue is. Any help is appreciated!

Thanks! 
Jay

**Comment by thurnherr** [comment]
This is a different error. Getting the result from DGIdb seems to work now. I will look into it later today. Here is what I get when I run your example on my computer:

> genes2 <- c("KRAS", "PIK3CA", "BRCA2")
> result <- queryDGIdb(genes = genes2)
Querying DGIDB...done!
Error in (function (..., deparse.level = 1)  : 
  number of columns of matrices must match (see arg 2)

**Comment by thurnherr** [comment]
I implemented a fix for the issue. Please allow a few hours for the newest version (**1.15.2**) to become available on [Bioconductor](http://bioconductor.org/packages/devel/bioc/html/rDGIdb.html) for download.

**Comment by jkanche** [comment]
I think it still has a few issues with parsing the api responses

```
> result <- queryDGIdb(genes = genes2)
Querying DGIDB...done!
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
 Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed 
```

Traceback

```
 Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed 
11.
stop("duplicate 'row.names' are not allowed") 
10.
`.rowNamesDF<-`(x, value = value) 
9.
`row.names<-.data.frame`(`*tmp*`, value = value[[1L]]) 
8.
`row.names<-`(`*tmp*`, value = value[[1L]]) 
7.
`dimnames<-.data.frame`(`*tmp*`, value = list(output[idx, ]$interactions[[1]]$drugName, 
    make.names(foundSources))) at rDGIdbResult.R#229
6.
`dimnames<-`(`*tmp*`, value = list(output[idx, ]$interactions[[1]]$drugName, 
    make.names(foundSources))) at rDGIdbResult.R#229
5.
FUN(X[[i]], ...) 
4.
lapply(theObject@data$geneName[sapply(theObject@data$interactions, 
    length) != 0], getResultSummary, theObject@data, uniqueSources) at rDGIdbResult.R#48
3.
setResultSummary(result) at rDGIdbResult.R#38
2.
setResultSummary(result) at queryDGIdb.R#84
1.
queryDGIdb(genes = genes2) 
```

**Comment by thurnherr** [comment]
I don't see this when I run it on my computer. Can you post your session info please?

> library(rDGIdb)
> genes2 <- c("KRAS", "PIK3CA", "BRCA2")
> result <- queryDGIdb(genes = genes2)
Querying DGIDB...done!

**Comment by jkanche** [comment]
Sorry forgot to update the gene list here 

`genes2 <- c("ESR")`

**Comment by thurnherr** [comment]
Thanks for the additional information. I updated the package, which should be available soon.
