### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by jbannon** [cbg-ethz/rDGIdb#5]
Running the vignette code 

` library(rDGIdb)
genes <- c("TNF", "AP1", "AP2", "XYZA")
result <- queryDGIdb(genes)
`
throws the following error:
`Querying DGIDB...Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL: no alternative certificate subject name matches target host name 'dgidb.genome.wustl.edu'`

Is this something that I can fix on my own or is this a backend issue?

**Comment by thurnherr** [comment]
Please install the [latest devel version from Bioconductor](https://www.bioconductor.org/packages/devel/bioc/html/rDGIdb.html). The release will happen later this month.
